const randomPrice = () => {
  return Math.floor(Math.random() * 500 + 40);
};

//generate random coordinates within a radius
const randomCoordinates = (lat, lng, radius) => {
  const r = radius / 111300; //about 111300 meters in one degree
  const u = Math.random();
  const v = Math.random();

  const w = r * Math.sqrt(u);
  const t = 2 * Math.PI * v;
  const x = w * Math.cos(t);
  const y = w * Math.sin(t);

  const newlat = y + lat;
  const newlon = x + lng;

  return [newlon, newlat];
};

const data = [{"title":"Anniversary","location":"Richmond"},
{"title":"Gerald","location":"Pesagen"},
{"title":"New Castle","location":"Rymanów"},
{"title":"Michigan","location":"Ystad"},
{"title":"Mccormick","location":"Qaşr Hallāl"},
{"title":"Laurel","location":"General Enrique Mosconi"},
{"title":"Eagan","location":"Luobuqiongzi"},
{"title":"Manitowish","location":"Hněvotín"},
{"title":"Continental","location":"Lescar"},
{"title":"Garrison","location":"Kaya"},
{"title":"Monica","location":"Xinshi"},
{"title":"Sutherland","location":"Benito Juarez"},
{"title":"Gateway","location":"Budagovo"},
{"title":"Lakeland","location":"Gaopeng"},
{"title":"Steensland","location":"Yao"},
{"title":"Bowman","location":"Kalininaul"},
{"title":"Debs","location":"Duwe"},
{"title":"Eggendart","location":"Manlio Fabio Altamirano"},
{"title":"Dixon","location":"Cawayan Bugtong"},
{"title":"Orin","location":"Kobelyaky"},
{"title":"Eastwood","location":"Františkovy Lázně"},
{"title":"Hudson","location":"Samdo"},
{"title":"Continental","location":"Alençon"},
{"title":"Ridgeview","location":"Houping"},
{"title":"Lyons","location":"Senduro"},
{"title":"Thierer","location":"Hufang"},
{"title":"Sunfield","location":"Gudang"},
{"title":"Westerfield","location":"Marseille"},
{"title":"Farmco","location":"Nanyulinxi"},
{"title":"Heath","location":"Harbutowice"},
{"title":"Barnett","location":"Zengtian"},
{"title":"Myrtle","location":"Izumi"},
{"title":"Corben","location":"Ādam"},
{"title":"Blue Bill Park","location":"Ra-ngae"},
{"title":"Crescent Oaks","location":"Mintian"},
{"title":"Lake View","location":"Velké Losiny"},
{"title":"Declaration","location":"Putinci"},
{"title":"Johnson","location":"Markowa"},
{"title":"Fieldstone","location":"Żychlin"},
{"title":"Carpenter","location":"Bohicon"},
{"title":"Veith","location":"Smolensk"},
{"title":"Fieldstone","location":"Richky"},
{"title":"Daystar","location":"Xinshao"},
{"title":"Sugar","location":"Quva"},
{"title":"Melody","location":"Compostela"},
{"title":"Gateway","location":"Sari"},
{"title":"Hauk","location":"Ujiie"},
{"title":"Novick","location":"Troyes"},
{"title":"Anthes","location":"Elena"},
{"title":"Mockingbird","location":"Lumbangan"},
{"title":"Continental","location":"Dajalorong"},
{"title":"Eastlawn","location":"Xujiaqiao"},
{"title":"Meadow Valley","location":"Mörön"},
{"title":"Hermina","location":"Terney"},
{"title":"Troy","location":"Leping"},
{"title":"Novick","location":"Paris 16"},
{"title":"Aberg","location":"Sztum"},
{"title":"Prentice","location":"Naḥf"},
{"title":"Messerschmidt","location":"Koslan"},
{"title":"Mariners Cove","location":"Machov"},
{"title":"Erie","location":"Huanghuatan"},
{"title":"Homewood","location":"Huangshagang"},
{"title":"Crowley","location":"Ágios Pétros"},
{"title":"Mendota","location":"Quibdó"},
{"title":"Fairfield","location":"Girihieum"},
{"title":"Russell","location":"Michałów"},
{"title":"Carpenter","location":"Plavy"},
{"title":"Bowman","location":"Dnipryany"},
{"title":"Debra","location":"Asahbadung"},
{"title":"Parkside","location":"Ciénaga de Oro"},
{"title":"Stone Corner","location":"Cocobeach"},
{"title":"Comanche","location":"Ostankinskiy"},
{"title":"Basil","location":"Mykolayiv"},
{"title":"Michigan","location":"Truskavets"},
{"title":"Sachtjen","location":"Messina"},
{"title":"Michigan","location":"Letuyi"},
{"title":"Mallory","location":"Baishuiyang"},
{"title":"Golf View","location":"Kotauneng"},
{"title":"Mitchell","location":"Baishui"},
{"title":"Cardinal","location":"Volodarsk"},
{"title":"Elmside","location":"Aisai"},
{"title":"Thackeray","location":"Ciasna"},
{"title":"Prairieview","location":"Rawannawi Village"},
{"title":"Hanson","location":"Saint-Claude"},
{"title":"Sutherland","location":"Owerri"},
{"title":"Merrick","location":"Medenychi"},
{"title":"Northland","location":"Hashimoto"},
{"title":"New Castle","location":"Yekaterinovka"},
{"title":"Village Green","location":"Palmerston North"},
{"title":"Westend","location":"Klyuchi"},
{"title":"Bashford","location":"Lebao"},
{"title":"Melody","location":"L’vovskiy"},
{"title":"Fremont","location":"Grenoble"},
{"title":"Onsgard","location":"Spárti"},
{"title":"Aberg","location":"Kafr Baţnā"},
{"title":"Lakewood Gardens","location":"Novaya Derevnya"},
{"title":"East","location":"Sandaoba"},
{"title":"Calypso","location":"Kutasari"},
{"title":"Badeau","location":"Cipeucang"},
{"title":"Magdeline","location":"Hedong"},
{"title":"Clove","location":"Kesabpur"},
{"title":"Dottie","location":"General José de San Martín"},
{"title":"Express","location":"Apeldoorn"},
{"title":"Brentwood","location":"Szubin"},
{"title":"Marcy","location":"Xiaojinkou"},
{"title":"New Castle","location":"Bato"},
{"title":"Havey","location":"Zverevo"},
{"title":"Anthes","location":"Klaeng"},
{"title":"Moulton","location":"Novoorsk"},
{"title":"Towne","location":"Tembol"},
{"title":"Maple","location":"Chiquimulilla"},
{"title":"Logan","location":"Aroa"},
{"title":"Northridge","location":"Härnösand"},
{"title":"Buell","location":"Dalu"},
{"title":"Tennessee","location":"Rentung"},
{"title":"Truax","location":"Bazar-Korgon"},
{"title":"Vidon","location":"Paicol"},
{"title":"Bluejay","location":"Houzhai"},
{"title":"Karstens","location":"Miaoya"},
{"title":"Clarendon","location":"Laxey"},
{"title":"Onsgard","location":"Nytva"},
{"title":"Arapahoe","location":"Dasongshu"},
{"title":"Birchwood","location":"Santa"},
{"title":"Armistice","location":"Kamphaeng Phet"},
{"title":"Crescent Oaks","location":"Santa Lucia"},
{"title":"Lillian","location":"Mount Ayliff"},
{"title":"Dorton","location":"Bautista"},
{"title":"Raven","location":"Haykashen"},
{"title":"Magdeline","location":"Inuotose"},
{"title":"Lyons","location":"Pictou"},
{"title":"Westerfield","location":"Buenavista"},
{"title":"Ruskin","location":"Naranjal"},
{"title":"Huxley","location":"Busia"},
{"title":"Gina","location":"Lunenburg"},
{"title":"Cordelia","location":"Ulyanovsk"},
{"title":"Hallows","location":"Tambawel"},
{"title":"Becker","location":"Dziemiany"},
{"title":"Lunder","location":"Parikkala"},
{"title":"Badeau","location":"Alejal"},
{"title":"Lakeland","location":"Phichit"},
{"title":"Gina","location":"Issy-les-Moulineaux"},
{"title":"Cottonwood","location":"Parung"},
{"title":"Eastlawn","location":"Podsineye"},
{"title":"Prairieview","location":"Krasnyy Oktyabr’"},
{"title":"Lunder","location":"Jiangqiao"},
{"title":"Roth","location":"Ani-e"},
{"title":"Northwestern","location":"Letlhakeng"},
{"title":"Graceland","location":"Ettal"},
{"title":"Lindbergh","location":"Marneuli"},
{"title":"Ruskin","location":"Tongyu"},
{"title":"Huxley","location":"Villa Nueva"},
{"title":"Grover","location":"Margamukti"},
{"title":"Bluestem","location":"Bologna"},
{"title":"Walton","location":"Longhua"},
{"title":"Crest Line","location":"Santo Niño"},
{"title":"Elmside","location":"Listowel"},
{"title":"Springs","location":"Magalalag"},
{"title":"Fisk","location":"Del Valle"},
{"title":"Main","location":"Konongo"},
{"title":"Fordem","location":"Gharavŭtí"},
{"title":"Morrow","location":"Lebu"},
{"title":"Merchant","location":"Xiluo"},
{"title":"Norway Maple","location":"Sirre"},
{"title":"Summit","location":"Ciduren"},
{"title":"Artisan","location":"Navotas"},
{"title":"Magdeline","location":"Kilkenny"},
{"title":"Summit","location":"Zipárion"},
{"title":"Toban","location":"Murcki"},
{"title":"Judy","location":"Guinsang-an"},
{"title":"Bultman","location":"Luanda"},
{"title":"Mayfield","location":"Jinli"},
{"title":"Dahle","location":"Monte Aprazível"},
{"title":"1st","location":"Walahir"},
{"title":"Armistice","location":"Migues"},
{"title":"Waxwing","location":"Gumdag"},
{"title":"Kingsford","location":"Chlewiska"},
{"title":"Delaware","location":"Huddinge"},
{"title":"Twin Pines","location":"Kowingir"},
{"title":"Schlimgen","location":"Jiaowei"},
{"title":"Browning","location":"Lamotrek"},
{"title":"Oak","location":"Ramón Castilla"},
{"title":"Clove","location":"Itanhandu"},
{"title":"Lakeland","location":"Sekampung"},
{"title":"Troy","location":"Shinpokh"},
{"title":"Dixon","location":"Béoumi"},
{"title":"Mockingbird","location":"Oliveira"},
{"title":"Northview","location":"Gucheng"},
{"title":"Elgar","location":"Beidaihehaibin"},
{"title":"Pepper Wood","location":"Eckerö"},
{"title":"Hauk","location":"Žďár nad Sázavou Druhy"},
{"title":"Lukken","location":"Kasamwa"},
{"title":"Shasta","location":"Além do Rio"},
{"title":"Cordelia","location":"Arrufó"},
{"title":"Reindahl","location":"Marabahan"},
{"title":"Darwin","location":"Atocha"},
{"title":"Melody","location":"São Miguel do Araguaia"},
{"title":"Tennyson","location":"Qingyun"},
{"title":"Paget","location":"Steinkjer"},
{"title":"Merchant","location":"Arapongas"},
{"title":"Sunbrook","location":"San Marcos"},
{"title":"Hooker","location":"Santa Catarina Barahona"},
{"title":"Fairfield","location":"Soroca"},
{"title":"Starling","location":"Singgit"},
{"title":"Atwood","location":"Pravdinsk"},
{"title":"Bonner","location":"Zhouxi"},
{"title":"Lyons","location":"Phra Phrom"},
{"title":"Artisan","location":"Masaran"},
{"title":"Katie","location":"Niquero"},
{"title":"Carberry","location":"Murcia"},
{"title":"Basil","location":"Najd al Jumā‘ī"},
{"title":"Tennyson","location":"Lawonda"},
{"title":"Spaight","location":"Xikou"},
{"title":"Lake View","location":"Prelog"},
{"title":"Macpherson","location":"Tyresö"},
{"title":"Holy Cross","location":"Valence"},
{"title":"Ridgeway","location":"Waco"},
{"title":"Clemons","location":"Gambaru"},
{"title":"Mitchell","location":"Teryayevo"},
{"title":"Sunnyside","location":"Lyon"},
{"title":"Di Loreto","location":"Moncton"},
{"title":"Pankratz","location":"Xuedian"},
{"title":"Namekagon","location":"Rennes"},
{"title":"Washington","location":"São José dos Campos"},
{"title":"Heffernan","location":"Mohelno"},
{"title":"Cordelia","location":"Granada"},
{"title":"Almo","location":"Jingang"},
{"title":"Grover","location":"Kediri"},
{"title":"Continental","location":"Bucheon-si"},
{"title":"Oak","location":"Qinglung"},
{"title":"Mcbride","location":"Samayac"},
{"title":"Jay","location":"Hotsk"},
{"title":"Meadow Valley","location":"Kesabpur"},
{"title":"Artisan","location":"Taihe"},
{"title":"Sunfield","location":"Zhongshan"},
{"title":"Old Shore","location":"Xunhe"},
{"title":"Thackeray","location":"Sumberdangdang"},
{"title":"Pepper Wood","location":"Thaton"},
{"title":"Old Gate","location":"Saint-Lin-Laurentides"},
{"title":"Grim","location":"Renshan"},
{"title":"Roth","location":"Mahikeng"},
{"title":"Lotheville","location":"Santa Rita do Sapucaí"},
{"title":"Longview","location":"Melaka"},
{"title":"Mesta","location":"Njivice"},
{"title":"Norway Maple","location":"Tuapukan"},
{"title":"Fulton","location":"Wuluo"},
{"title":"Harbort","location":"Vol’nyy Aul"},
{"title":"Vahlen","location":"Pajak"},
{"title":"Dennis","location":"Xikou"},
{"title":"Tomscot","location":"Shicheng"},
{"title":"Northfield","location":"Herby"},
{"title":"Emmet","location":"Torslanda"},
{"title":"Beilfuss","location":"Dailekh"},
{"title":"Talisman","location":"Changsheng"},
{"title":"Bowman","location":"Guadalupe Victoria"},
{"title":"Harbort","location":"Kālia"},
{"title":"Utah","location":"Montalvo"},
{"title":"Garrison","location":"Kandangsapi"},
{"title":"Caliangt","location":"Kanluran"},
{"title":"Russell","location":"Guernica"},
{"title":"Maryland","location":"Ciheras"},
{"title":"Portage","location":"Dingbu"},
{"title":"Lien","location":"Nancheng"},
{"title":"Veith","location":"P’asanauri"},
{"title":"Claremont","location":"Xiashuitou"},
{"title":"Kenwood","location":"Vitória da Conquista"},
{"title":"Cottonwood","location":"Tai’an"},
{"title":"South","location":"Chejiazhuang"},
{"title":"Farwell","location":"Upper San Mateo"},
{"title":"Monterey","location":"Duobao"},
{"title":"Quincy","location":"Turija"},
{"title":"Birchwood","location":"Santa Maria"},
{"title":"Elgar","location":"Lotoshino"},
{"title":"Hooker","location":"Ural"},
{"title":"Green","location":"Verkhnye Syn’ovydne"},
{"title":"Lighthouse Bay","location":"Tlumach"},
{"title":"Kropf","location":"Kangping"},
{"title":"Pennsylvania","location":"Wangcun"},
{"title":"Katie","location":"Shangcun"},
{"title":"Sloan","location":"Biito"},
{"title":"Cordelia","location":"Jinta"},
{"title":"Burrows","location":"Xinan"},
{"title":"Fisk","location":"Glória do Goitá"},
{"title":"Nancy","location":"Xialiao"},
{"title":"Corry","location":"Orange Farm"},
{"title":"Oak Valley","location":"Bílina Kyselka"},
{"title":"Cascade","location":"Hoxtolgay"},
{"title":"Lake View","location":"Volksrust"},
{"title":"Melrose","location":"Kayan Hulu"},
{"title":"Ryan","location":"Libas"},
{"title":"Larry","location":"Złoczew"},
{"title":"Hollow Ridge","location":"Corpus"},
{"title":"Vidon","location":"Binucayan"},
{"title":"Old Shore","location":"Sidu"},
{"title":"3rd","location":"Porto Feliz"},
{"title":"Westerfield","location":"Borgo Maggiore"},
{"title":"Jenifer","location":"Mandalgovi"},
{"title":"Mariners Cove","location":"Tiancheng"},
{"title":"Bunting","location":"Holboo"},
{"title":"Acker","location":"Sanfang"},
{"title":"Luster","location":"Perdões"}].map(item => ({
  ...item, "image": "https://source.unsplash.com/800x600/?woods,camps",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "price": randomPrice(),
  "author": '61b1c71c96187ce6833b9320',
  "image": [ { "url" : "https://res.cloudinary.com/djmfik7ni/image/upload/v1639480966/Inshivir/t4uou8t6i2yfr1pfiaax.png", "filename" : "Inshivir/t4uou8t6i2yfr1pfiaax"} ],
  "geometry": {
    "type": "Point",
    "coordinates": randomCoordinates(22.830982779347984, 78.2360325972813, 1000000)
  }
  
}));

module.exports = data;

// "geometry" : 
// { 
//   "type" : "Point", 
//   "coordinates" : [ 76.69389, 11.40861 ] 
// }


